package: warehouse
version: '1.1.beta'
author: Friends Of REDAXO

page:
    title: Warehouse
    perm: warehouse[params]
    pjax: true    
    icon: rex-icon fa-shopping-cart
    subpages:
        settings: { title: 'Einstellungen' }
        setup: { title: 'Setup', perm: admin }
        info: { title: 'Info', itemclass: pull-right }

requires:
    redaxo: '^5.11'
    packages:
        structure: '^2.0'
        yform/manager: '>3'

        
