package: warehouse
version: '2.0.0-dev-2025-03-22'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/warehouse

page:
    title: translate:warehouse_settings
    perm: warehouse
    pjax: true
    block: warehouse
    prio: 0
    icon: rex-icon fa-shopping-cart
    subpages:
        settings:
            title: translate:warehouse_settings_shop
            perm: warehouse[settings]
            icon: rex-icon fa-cog
            itemclass: pull-right
            subpages:
                general:
                    title: translate:warehouse_settings_general
                    perm: warehouse[settings]
                    icon: rex-icon fa-wrench
                domain:
                    title: translate:warehouse_settings_domain
                    perm: warehouse[setup]
                    icon: rex-icon fa-sitemap
                tax:
                    title: translate:warehouse_settings_tax
                    perm: warehouse[settings]
                    icon: rex-icon fa-percent
                discount:
                    title: translate:warehouse_settings_discount
                    perm: warehouse[settings]
                    icon: rex-icon fa-tag
                shipping:
                    title: translate:warehouse_shipping
                    perm: warehouse[shipping]
                    icon: rex-icon fa-truck
                setup:
                    title: translate:warehouse_settings_setup
                    perm: warehouse[setup]
                    icon: rex-icon fa-cogs

        shipping:
            title: translate:warehouse_shipping
            perm: warehouse[shipping]
            icon: rex-icon fa-truck
            subpages:
                settings:
                    title: translate:warehouse_settings_shipping
                    perm: warehouse[shipping]
                    icon: rex-icon fa-cogs
                zones:
                    title: translate:warehouse_zones
                    perm: warehouse[shipping]
                    icon: rex-icon fa-globe
                countries:
                    title: translate:warehouse_countries
                    perm: warehouse[shipping]
                    icon: rex-icon fa-flag
        payment:
            title: translate:warehouse_settings_payment
            perm: warehouse[payment]
            icon: rex-icon fa-credit-card
            subpages:
                paypal:
                    title: translate:warehouse_settings_paypal
                    perm: warehouse[payment]
                    icon: rex-icon fa-paypal
                giropay:
                    title: translate:warehouse_settings_giropay
                    perm: warehouse[payment]
                    icon: rex-icon fa-euro
                wallee:
                    title: translate:warehouse_settings_wallee
                    perm: warehouse[payment]
                    icon: rex-icon fa-money
        docs:
            title: translate:warehouse_docs
            perm: warehouse[docs]
            icon: rex-icon fa-info-circle
            itemclass: pull-right

pages:
    article:
        block: warehouse
        title: translate:warehouse_article
    article_variant:
        block: warehouse
        title: translate:warehouse_article_variant
    category:
        block: warehouse
        title: translate:warehouse_category
    order:
        block: warehouse
        title: translate:warehouse_order
    country:
        block: warehouse
        title: translate:warehouse_country


requires:
    redaxo: '^5.17'
    php:
        version: '>=8.3,<9'
    packages:
        structure: '^2.0'
        yform: '^4.1'

default_config:
    store_name: 
    store_country_code: "DE"

    currency: "EUR"
    currency_symbol: "€"
    country_codes: "DE"
    cart_mode: "cart"
    editor: 'class="form-control redactor-editor--default"'
    check_weight: 0

    email_template_customer: 
    email_template_seller:
    order_email:

    # Rabatt
    global_discount_text: ''
    global_discount: 0

    # Paypal Einstellungen
    paypal_client_id:
    paypal_secret:
    sandboxmode: 0
    paypal_sandbox_client_id:
    paypal_sandbox_secret:
    paypal_getparams:
    paypal_page_start:
    paypal_page_success:
    paypal_page_error: 

    # Versandkosten
    minimum_order_value: 0
    shipping_fee: 0
    free_shipping_from: 0
    shipping_calculation_mode: ''
    
