package: warehouse
version: '2.0.0-dev-2025-07-29'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/warehouse

page:
    title: translate:warehouse.title
    perm: warehouse
    main: true
    block: system
    prio: 2
    icon: rex-icon fa-shopping-cart
    subpages:
        order:
            title: translate:warehouse_order
            icon: rex-icon fa-shopping-cart
            subpages:
                dashboard:
                    title: translate:warehouse_order_dashboard
                    icon: rex-icon fa-chart-line
                list:
                    title: translate:warehouse_order_list
                    icon: rex-icon fa-list
                details:
                    title: translate:warehouse_order_details
                    icon: rex-icon fa-shopping-cart
                customer:
                    title: translate:warehouse_customer
                    icon: rex-icon fa-id-card
                customer_address:
                    title: translate:warehouse_customer_address
                    icon: rex-icon fa-truck-arrow-right

pages:
    system/log/warehouse:
        title: translate:warehouse_log
        perm: admin
    article:
        title: translate:warehouse_article
        icon: rex-icon fa-cube
        pjax: false
    article_variant:
        title: translate:warehouse_article_variant
        icon: rex-icon fa-cubes
        pjax: false
    category:
        title: translate:warehouse_category
        icon: rex-icon fa-tag
        pjax: false
    search:
        title: translate:warehouse_search
        icon: rex-icon fa-search
    settings:
        title: translate:warehouse_settings_shop
        perm: warehouse[settings]
        icon: rex-icon fa-cog
        itemclass: pull-right
        subpages:
            general:
                title: translate:warehouse_settings_general
                perm: warehouse[settings]
                icon: rex-icon fa-wrench
            payment:
                title: translate:warehouse_settings_payment
                perm: warehouse[payment]
                icon: rex-icon fa-credit-card
            shipping:
                title: translate:warehouse_shipping
                perm: warehouse[shipping]
                icon: rex-icon fa-truck
            domain:
                title: translate:warehouse_settings_domain
                perm: warehouse[setup]
                icon: rex-icon fa-sitemap
            discount:
                title: translate:warehouse_settings_discount
                perm: warehouse[settings]
                icon: rex-icon fa-tag
            documents:
                title: translate:warehouse_settings_documents
                perm: warehouse[docs]
                icon: rex-icon fa-file-alt
            label:
                title: translate:warehouse_settings_label
                perm: warehouse[settings]
                icon: rex-icon fa-text
            log:
                title: translate:warehouse_settings_log
                perm: warehouse[log]
                icon: rex-icon fa-history
            setup:
                title: translate:warehouse_settings_setup
                perm: warehouse[setup]
                icon: rex-icon fa-cogs
    docs:
        title: translate:warehouse_docs
        perm: warehouse[docs]
        icon: rex-icon fa-info-circle
        itemclass: pull-right

requires:
    redaxo: '^5.18.3'
    php:
        version: '>=8.3,<9'
    packages:
        structure: '^2.0'
        yform: '>=4.1,<6'
        yform_field: '^2.11.1'

# Wenn Warehouse 1.x installiert ist, dann abbrechen - es ist keine Migration vorgesehen.
conflicts:
    packages:
        warehouse: '<1.99.999'

default_config:

    # Grundeinstellungen
    store_name: 
    store_country_code: "DE"

    currency: "EUR"
    currency_symbol: "€"
    country_codes: "DE"
    cart_mode: "cart"
    editor: ''
    framework: 'bootstrap5'
    ycom_mode: 'guest_only'
    price_input_mode: 'net' # 'net' oder 'gross' – legt fest, ob Preiseingabe netto oder brutto ist
    delivery_note_number: 1
    invoice_number: 1
    order_number: 1

    fallback_category_image: 'warehouse_placeholder_category.jpeg'
    fallback_article_image: 'warehouse_placeholder_article.jpeg'

    # E-Mail Einstellungen
    email_template_customer: 'warehouse_order_customer'
    email_template_seller: 'warehouse_order_seller'
    order_email: 

    # Paypal Einstellungen
    allowed_payment_options: "|prepayment|invoice|direct_debit|"
    paypal_client_id:
    paypal_secret:
    sandboxmode: 0
    paypal_sandbox_client_id:
    paypal_sandbox_secret:
    paypal_getparams:
    paypal_page_start:
    paypal_page_success:
    paypal_page_error: 

    # Versandkosten
    minimum_order_value: 0
    shipping_fee: 0
    free_shipping_from: 0
    shipping_calculation_mode: ''
    
    # Labels
    label_cart: 'Warenkorb'
    labeL_cart_empty: 'Der Warenkorb ist leer'
    label_article: 'Artikel'
    label_back_to_cart: 'Zurück zum Warenkorb'
    label_cart_empty: 'Der Warenkorb ist leer.'
    label_cart_empty_confirm: 'Sind Sie sicher, dass Sie den Warenkorb leeren möchten?'
    label_cart_remove_item_confirm: 'Sind Sie sicher, dass Sie den gewählten Artikel entfernen möchten?'
    label_cart_subtotal: 'Zwischensumme'
    label_cart_total: 'Summe'
    label_cart_total_weight: 'Gesamtgewicht'
    label_checkout: 'Kasse'
    label_checkout_address: 'Adresse'
    label_checkout_instant: 'Sofort kaufen'
    label_checkout_payment: 'Bezahlmethode'
    label_next: ''
    label_payment_type: 'Bezahloptionen'
    label_price: 'Einzelpreis'
    label_quantity: 'Anzahl'
    label_remove_from_cart: 'Entfernen'
    label_shipping_costs: 'Versandkosten'
    label_shipping_costs_free: 'Ohne Versandkosten'
    label_shipping_costs_weight: 'Versandkosten nach Gewicht'
    label_total: 'Gesamtpreis'
    label_order_number: 'Bestellnummer'
