package: warehouse
version: '2.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/friendsofredaxo/warehouse

page:
    title: Warehouse
    perm: warehouse[params]
    pjax: true    
    icon: rex-icon fa-shopping-cart
    subpages:
        settings: { title: 'Einstellungen' }
        setup: { title: 'Setup', perm: admin }
        info: { title: 'Info', itemclass: pull-right }

requires:
    redaxo: '^5.17'
    php:
        version: '>=8.3,<9'
    packages:
        structure: '^2.0'
        yform: '^4.1'

default_config:
    store_name: 
    store_country_code: "DE"
    cart_page:
    address_page:
    order_page:
    thankyou_page:
    payment_error: 
    shippinginfo_page: 
    my_orders_page:
    currency: "EUR"
    currency_symbol: "€"
    country_codes: "DE,AT,CH"
