package: warehouse
version: '2.0.0-dev-2025-06-29'
author: FriendsOfREDAXO
supportpage: https://github.com/FriendsOfREDAXO/warehouse

page:
    title: translate:warehouse_settings
    perm: warehouse
    pjax: false
    block: warehouse
    prio: 0
    icon: rex-icon fa-shopping-cart
    subpages:
        order:
            block: warehouse
            title: translate:warehouse_order
            icon: rex-icon fa-shopping-cart
            subpages:
                dashboard:
                    title: translate:warehouse_order_dashboard
                    icon: rex-icon fa-chart-line
                list:
                    title: translate:warehouse_order_list
                    icon: rex-icon fa-list
                details:
                    title: translate:warehouse_order_details
                    icon: rex-icon fa-shopping-cart
                customer:
                    title: translate:warehouse_customer
                    icon: rex-icon fa-id-card
                customer_address:
                    title: translate:warehouse_customer_address
                    icon: rex-icon fa-truck-arrow-right

pages:
    system/log/warehouse:
        title: translate:warehouse_log
        perm: admin
        
    article:
        block: warehouse
        title: translate:warehouse_article
        icon: rex-icon fa-cube
        pjax: false
    article_variant:
        block: warehouse
        title: translate:warehouse_article_variant
        icon: rex-icon fa-cubes
        pjax: false
    category:
        block: warehouse
        title: translate:warehouse_category
        icon: rex-icon fa-tag
        pjax: false
    search:
        block: warehouse
        title: translate:warehouse_search
        icon: rex-icon fa-search
    settings:
        title: translate:warehouse_settings_shop
        perm: warehouse[settings]
        icon: rex-icon fa-cog
        itemclass: pull-right
        subpages:
            general:
                title: translate:warehouse_settings_general
                perm: warehouse[settings]
                icon: rex-icon fa-wrench
            payment:
                title: translate:warehouse_settings_payment
                perm: warehouse[payment]
                icon: rex-icon fa-credit-card
            shipping:
                title: translate:warehouse_shipping
                perm: warehouse[shipping]
                icon: rex-icon fa-truck
            domain:
                title: translate:warehouse_settings_domain
                perm: warehouse[setup]
                icon: rex-icon fa-sitemap
            discount:
                title: translate:warehouse_settings_discount
                perm: warehouse[settings]
                icon: rex-icon fa-tag
            label:
                title: translate:warehouse_settings_label
                perm: warehouse[settings]
                icon: rex-icon fa-text
            log:
                title: translate:warehouse_settings_log
                perm: warehouse[log]
                icon: rex-icon fa-history
            setup:
                title: translate:warehouse_settings_setup
                perm: warehouse[setup]
                icon: rex-icon fa-cogs
    docs:
        title: translate:warehouse_docs
        perm: warehouse[docs]
        icon: rex-icon fa-info-circle
        itemclass: pull-right

requires:
    redaxo: '^5.18.3'
    php:
        version: '>=8.3,<9'
    packages:
        structure: '^2.0'
        yform: '>=4.1,<6'
        yform_field: '^2.11.1'

# Wenn Warehouse 1.x installiert ist, dann abbrechen - es ist keine Migration vorgesehen.
conflicts:
    packages:
        warehouse: '<1.99.999'

default_config:

    # Grundeinstellungen
    store_name: 
    store_country_code: "DE"

    currency: "EUR"
    currency_symbol: "€"
    country_codes: "DE"
    cart_mode: "cart"
    editor: ''
    framework: 'bootstrap5'
    tax_options: '19,7,0'
    ycom_mode: 'guest_only'
    price_input_mode: 'net' # 'net' oder 'gross' – legt fest, ob Preiseingabe netto oder brutto ist
    delivery_note_number: 1
    invoice_number: 1
    order_number: 1

    fallback_category_image: 'warehouse_placeholder_category.jpeg'
    fallback_article_image: 'warehouse_placeholder_article.jpeg'

    # E-Mail Einstellungen
    email_template_customer: 'warehouse_order_customer'
    email_template_seller: 'warehouse_order_seller'
    order_email: 

    # Paypal Einstellungen
    paypal_client_id:
    paypal_secret:
    sandboxmode: 0
    paypal_sandbox_client_id:
    paypal_sandbox_secret:
    paypal_getparams:
    paypal_page_start:
    paypal_page_success:
    paypal_page_error: 

    # Versandkosten
    minimum_order_value: 0
    shipping_fee: 0
    free_shipping_from: 0
    shipping_calculation_mode: ''
    
    # Labels
    label_cart: 'Warenkorb'
    labeL_cart_empty: 'Der Warenkorb ist leer'
    label_shipping_costs: 'Versandkosten'
