package: warehouse
version: '2.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/friendsofredaxo/warehouse

page:
    title: Warehouse
    perm: warehouse[params]
    pjax: true    
    icon: rex-icon fa-shopping-cart
    subpages:
        settings: { title: 'Einstellungen' }
        setup: { title: 'Setup', perm: admin }
        info: { title: 'Info', itemclass: pull-right }

requires:
    redaxo: '^5.17'
    php:
        version: '>=8.3,<9'
    packages:
        structure: '^2.0'
        yform: '^4.1'

default_config:
    store_name: 
    store_country_code: "DE"
    cart_page:
    address_page:
    order_page:
    thankyou_page:
    payment_error: 
    shippinginfo_page: 
    my_orders_page:
    currency: "EUR"
    currency_symbol: "€"
    country_codes: "DE,AT,CH"
    cart_mode: "cart"
    check_weight: 0
    tax_value: 19
    tax_value_1: 7
    tax_value_2: 0
    tax_value_3: 0
    tax_value_4: 0

    email_template_customer: 
    email_template_seller:
    order_email:

    # Rabatt
    global_discount_text: ''
    global_discount: 0

    # Paypal Einstellungen
    paypal_client_id:
    paypal_secret:
    sandboxmode: 0
    paypal_sandbox_client_id:
    paypal_sandbox_secret:
    paypal_getparams:
    paypal_page_start:
    paypal_page_success:
    paypal_page_error: 

    # To-Do: Wallee
    
    # Frachtkosten
    shipping: 
    shipping_mode: 0
    shipping_parameters:
    