<?php

rex_sql_table::get(rex::getTable('warehouse_article'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('name', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('availability', 'varchar(191)'))
    ->ensureColumn(new rex_sql_column('category_id', 'int(10) unsigned'))
    ->ensureColumn(new rex_sql_column('status', 'tinyint(1)'))
    ->ensureColumn(new rex_sql_column('price', 'decimal(10,2)', true))
    ->ensureColumn(new rex_sql_column('tax', 'tinyint(1)'))
    ->ensureColumn(new rex_sql_column('price_text', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('weight', 'decimal(10,2)', true))
    ->ensureColumn(new rex_sql_column('short_text', 'text'))
    ->ensureColumn(new rex_sql_column('text', 'text'))
    ->ensureColumn(new rex_sql_column('image', 'text'))
    ->ensureColumn(new rex_sql_column('gallery', 'text'))
    ->ensureColumn(new rex_sql_column('uuid', 'varchar(36)'))
    ->ensureColumn(new rex_sql_column('updatedate', 'datetime'))
    ->ensure();

rex_sql_table::get(rex::getTable('warehouse_article_variant'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('article_id', 'int(10) unsigned'))
    ->ensureColumn(new rex_sql_column('name', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('price', 'decimal(10,2)', true))
    ->ensureColumn(new rex_sql_column('bulk_prices', 'text'))
    ->ensureColumn(new rex_sql_column('weight', 'decimal(10,2)', true))
    ->ensureColumn(new rex_sql_column('prio', 'int(11)'))
    ->ensureColumn(new rex_sql_column('availability', 'varchar(191)'))
    ->ensureColumn(new rex_sql_column('image', 'text'))
    ->ensureColumn(new rex_sql_column('status', 'text'))
    ->ensureColumn(new rex_sql_column('uuid', 'varchar(36)'))
    ->ensure();

rex_sql_table::get(rex::getTable('warehouse_category'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('prio', 'int(11)'))
    ->ensureColumn(new rex_sql_column('parent_id', 'int(10) unsigned'))
    ->ensureColumn(new rex_sql_column('name', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('teaser', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('image', 'text'))
    ->ensureColumn(new rex_sql_column('text', 'text'))
    ->ensureColumn(new rex_sql_column('status', 'tinyint(1)'))
    ->ensureColumn(new rex_sql_column('uuid', 'varchar(36)'))
    ->ensureColumn(new rex_sql_column('updatedate', 'datetime'))
    ->ensureColumn(new rex_sql_column('link_intern', 'text'))
    ->ensure();

rex_sql_table::get(rex::getTable('warehouse_order'))
    ->ensurePrimaryIdColumn()
    ->ensureColumn(new rex_sql_column('salutation', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('firstname', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('lastname', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('company', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('address', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('zip', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('city', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('country', 'text'))
    ->ensureColumn(new rex_sql_column('email', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('createdate', 'datetime'))
    ->ensureColumn(new rex_sql_column('paypal_id', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('payment_id', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('paypal_confirm_token', 'text'))
    ->ensureColumn(new rex_sql_column('payment_confirm', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('order_text', 'text'))
    ->ensureColumn(new rex_sql_column('order_json', 'text'))
    ->ensureColumn(new rex_sql_column('order_total', 'decimal(10,2)', true))
    ->ensureColumn(new rex_sql_column('ycom_userid', 'int(11)'))
    ->ensureColumn(new rex_sql_column('payment_type', 'varchar(191)', false, ''))
    ->ensureColumn(new rex_sql_column('payed', 'tinyint(1)'))
    ->ensureColumn(new rex_sql_column('imported', 'tinyint(1)', false, '0'))
    ->ensure();
